### ISSUE TITLE
For aggregated columns show 0-point using a line across rows 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/org.caleydo.view.lineup#10]
For input data on a negative range, show the point the data has to pass to be To show the point the data has to pass to be positive on average. Here is a sketch: 

![image](https://cloud.githubusercontent.com/assets/2039375/8230830/20cb7fec-15c4-11e5-90fb-b2762fd02f21.png)
Not quite sure how well that works for mixed scales, though.

**Comment by sgratzl** [comment]
a problem is that mixed/combined columns are always defined in the range [0,1] since the work on the basis of normalized values not the raw ones. So, there is no automatic way determining which is the 0 line position for the combined bar.

**Comment by alexsb** [comment]
Well, you'd have to back to the raw data and get the information what a 0 value would correspond to.

**Comment by sgratzl** [comment]
doesn't work in the general case with arbitrary mappings and nesting...

**Comment by alexsb** [comment]
Why? Can you give a counter-example? 

But anyways, that's probably not super-relevant. We could show that only if we have exclusively +/- items?

**Comment by sgratzl** [comment]
sample dataset: 

``` R
test = cbind(a=runif(100,-1,3),b=runif(100,-2,2),c=runif(100,-2,2),d=runif(100,-1,1))
```

![preview](https://cloud.githubusercontent.com/assets/4129778/8253334/072830b4-168f-11e5-9e15-d8b3ff182751.png)

**Comment by alexsb** [comment]
Cool. Not super-easy to read, but if you know what you're looking for it works. What do you think?

**Comment by sgratzl** [comment]
not easy to read. But, that is the drawback of using a stacked bar for encoding negative contributions. 

The basic task was: "The only thing is that for us it is important to talk about whether GEP itself is positive or negative and that information would be lost in the lineup visualization."

Therefore, we might move the zero combined line above the stacked bars. 

The zero point indicators in the bar irritate me, since you can't really see the pattern except for the yellow column due to alignment issues.

**Comment by alexsb** [comment]
We could always cross-hatch the negative portion of the bar?

**Comment by sgratzl** [comment]
> We could always cross/hatch the negative portion of the bar? 

you mean the whole negative part of the stacked bar? - not that easy form an implementation point of view. Maybe with an overlay over the bars but the individual stacked bar elements are rendered independently.
