### ISSUE TITLE
Add synchronized scrolling mode

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.lineup#2]
In order to have meaningful slopes where the angle corresponds to the change in position between the snapshots, it is necessary to synchronize the snapshot scroll positions. Users should be able to turn off/on this feature.

**Comment by sgratzl** [comment]
the right most scrollbar + mouse wheel, perform a global scroll. That means if you scroll it down 3 steps, all snapshots scroll down 3 steps, if possible. 

the underlying problem is the scroll into view feature, when the user select an entry, the row layout including scrolling scrolling, will be adapted such that the selected item is visible. 

it should be therefore possible to deactivate this feature or apply it just for the relevant snapshot and use the target position/scrollposition in the other views
